blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/Xitee1/PowerBoard/discussions/categories/ideas
    about: Please use the discussions section to request features.
